/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.firebase;
/*
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name="TiFirebase", id="ti.firebase")
public class TiFirebaseModule extends KrollModule
// Standard Debugging variables
private static final String LCAT = "FirebaseModule";

public static boolean debuggable = false;

public TiFirebaseModule() {
	super();
}

@Kroll.onAppCreate
public static void onAppCreate(TiApplication app) {
	Log.d(LCAT, "inside onAppCreate");
	// put module init code that needs to run when the application is
	// created
}

@Kroll.method
public boolean configure() {
	try{
		//final Fabric fabric = new Fabric.Builder(TiApplication.getInstance()).kits(new Crashlytics()).debuggable(debuggable).build();
		//Fabric.with(fabric);
		return true;
	}catch(Exception exp){
		Log.e(LCAT, exp.getMessage());
		return false;
	}
}
}
*/